# Generated by Django 3.1.4 on 2021-03-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210331_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('sports', 'Sports'), ('international', 'International'), ('pakistan', 'Pakistan')], max_length=50, null=True),
        ),
    ]
