# Generated by Django 3.1.4 on 2021-03-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210331_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='BlogImages/'),
        ),
    ]
