# Generated by Django 3.1.4 on 2021-03-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_blog_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='thumb',
            new_name='center_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='BlogImages/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='BlogImages/'),
        ),
        migrations.DeleteModel(
            name='BlogImages',
        ),
    ]
