# Generated by Django 3.1.4 on 2021-04-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210331_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.CharField(blank=True, choices=[('urdu', 'Urdu'), ('english', 'English')], max_length=50, null=True),
        ),
    ]
