# Generated by Django 3.1.4 on 2021-04-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_blog_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
